version: '3.5'

services:
  redis:
    image: redis
    container_name: sayphr-redis
    ports:
      - "6379:6379"
  app:
    container_name: sayphr-api
    links:
      - redis
    depends_on:
      - redis
    build:
      context: .
      target: dev
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env